### PR TITLE
Fix DTStart not changing internal rrules and exrules

### PR DESCRIPTION
**Pull request by srikrsna**
#20

### CODE REVIEW

**Comment by srikrsna** [comment]
Is there a problem with this pr?

**Comment by zensh** [comment]
image

**Comment by srikrsna** [comment]
@zensh Thank you for that. I really don't see the suggestion. There's something wrong with Github. Anyhow may I ask why is it not necessary for exrule?

**Comment by srikrsna** [comment]
@zensh Not setting it for ex rule will again be inconsistent as it is being set when the rule rule is parsed  from a string [here](https://github.com/teambition/rrule-go/blob/c53b0d05b9ec81622ba8b598584a931146ad248f/str.go#L305)

**Comment by zensh** [comment]
@srikrsna You are right

**Pull request merged**
